apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
stringData:
  credentials: "foo"
---
apiVersion: bitbucket-server.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  baseURL: https://bitbucket.company.example.com
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
